# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-04 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
