# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0002_song_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default=2, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='url',
            field=models.FileField(upload_to='songs'),
        ),
    ]
