# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0003_auto_20160405_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyric',
            field=models.FileField(default=1, upload_to='lyric'),
            preserve_default=False,
        ),
    ]
