# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyric',
        ),
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
        migrations.AddField(
            model_name='song',
            name='song_id',
            field=models.CharField(default=datetime.datetime(2016, 4, 26, 9, 34, 23, 550683, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
