# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plat', '0006_auto_20160426_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
